# This is a basic workflow to help you get started with Actions

name: Deploy to Raspberry Pi

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
            cache: 'pipenv'

      - name: Install pipenv
        run: curl https://raw.githubusercontent.com/pypa/pipenv/master/get-pipenv.py | python
      - run: pipenv install

      - name: Install dependencies
        run: pipenv install -r requirements.txt
      
      
    

  deploy:
    runs-on: self-hosted
    needs: build
    
    steps:
      - name: Kill systemd irrigation service
        run: |
          sudo systemctl stop irrigation.service
          python irrigation.py