# This is a basic workflow to help you get started with Actions

name: Deploy to Raspberry Pi

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python environment
        run: |
          if [ ! -d "env" ]; then
            python3 -m venv env
          fi
          source env/bin/activate
          python -m pip install --upgrade pip

      - name: Install dependencies
        run: |
          source env/bin/activate
          pip install -r requirements.txt
          
  deploy:
    runs-on: self-hosted
    needs: build
    
    steps:
      - name: Kill systemd irrigation service
        run: |
          sudo systemctl restart irrigation.service